name: 'Notes-Demo'
services:
  search-service:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.12.0'
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: '-Xmx1G'
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
  cloaked-search:
    image: 'gcr.io/ironcore-images/cloaked-search:2.8.1'
    ports:
      - 8675:8675
    depends_on:
      - search-service
      - tsp
    volumes:
      - type: bind
        source: ./try-cloaked-search-conf.json
        target: /app/deploy.json
      - type: bind
        source: ./indices
        target: /app/indices
      - type: bind
        source: ./example.key
        target: /secrets/cloaked-search/key1
  tsp:
    image: 'gcr.io/ironcore-images/tenant-security-proxy:4.14'
    env_file:
      - blah
    ports:
      - 32804:7777
  s3:
    image: 'gcr.io/ironcore-images/saas-shield-s3-proxy:1.4'
    env_file:
      - ../.s3.env
    environment:
      TSP_URL: 'tsp'
      PROXY_DNS_NAME: 'the hostname of the VM running the S3 proxy. This is the address the clients will use to send requests to the proxy'
    depends_on:
      - tsp
    ports:
      - 8080:8080
