name: 'Notes-Demo'
services:
  tsp:
    image: 'gcr.io/ironcore-images/tenant-security-proxy:4.14'
    env_file:
      - ./NotesApp.conf
    ports:
      - 32804:7777
  search-service:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.12.0'
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: '-Xmx1G'
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
  cloaked-search:
    image: 'gcr.io/ironcore-images/cloaked-search:2.8.1'
    ports:
      - 8675:8675
    depends_on:
      - search-service
      - tsp
    volumes:
      - type: bind
        source: ./cloaked-search-conf.json
        target: /app/deploy.json
      - type: bind
        source: ./indices
        target: /app/indices
      - type: bind
        source: ../tsp-api-key
        target: /secrets/tsp-api-key
  s3:
    image: 'gcr.io/ironcore-images/saas-shield-s3-proxy:1.4'
    env_file:
      - ../.env.s3
    environment:
      TSP_URL: 'http://tsp:7777'
      PROXY_DNS_NAME: 's3'
    depends_on:
      - tsp
    ports:
      - 8080:8080
